name: route2
description: A client + server routing library for Dart 2.x
version: 0.1.1
author: "Dart Authors <misc@dartlang.org>"
homepage: https://github.com/rossalbertson/route2

environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  #  browser: '>=0.9.0<2.0.0'
  logging: '>=0.9.0<2.0.0'

dev_dependencies:
  #  unittest: '>=0.9.0<2.0.0'
  test: ^1.0.0
  path: '>=0.9.0<2.0.0'
